config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }, path: "auth", path_names: {
    sign_in: "login",
    sign_out: "logout",
    password: "secret",
    confirmation: "verification",
    unlock: "unblock",
    registration: "register",
    sign_up: "cmon_let_me_in"
  }

  namespace :api do
    resources :users
    resources :books
  end

  resources :books do
    member do
      post :borrow
      resources :comments, only: [ :destroy ]
    end
  end

  resources :borrowed_books, only: [ :index, :show, :update ] do
    member do
      post :return
      post :comment
    end
  end

  root to: "home#index"
end

app/controllers/borrowed_books_controller.rb
class BorrowedBooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [ :show, :return, :comment ]

  def index
    @categories = Category.all
    @borrowed_books = current_user.borrowed_books
  end

  def show
    @remaining_time = @book.borrowered_at + 2.weeks - Time.current
  end

  def return
    if @book.borrower_id == current_user.id
      @book.update(borrower_id: nil, borrowered_at: nil)
      flash[:notice] = "You have successfully returned the book."
    else
      flash[:alert] = "You cannot return this book."
    end
    redirect_to borrowed_books_path
  end

  def comment
    if @book.borrower_id == current_user.id
      @book.comments.create(content: params[:comment], user: current_user)
      flash[:notice] = "Your comment has been added."
    else
      flash[:alert] = "You cannot comment on this book."
    end
    redirect_to borrowed_books_path(@book)
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end
end

app/helpers/borrowed_books_helper.rb
module BorrowedBooksHelper
end

app/views/borrowed_books/index.html.erb
<%= render 'shared/category_filter' %>
<h1>My Borrowed Books</h1>
<% if @borrowed_books.any? %>
  <table class="table table-striped">
    <thead class='table-dark'>
      <tr>
        <th>Title</th>
        <th>Borrowed At</th>
        <th>Time Remaining</th>
        <th>My Comments</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @borrowed_books.each do |book| %>
        <tr class='align-middle'>
          <td> 
            <%= link_to book.title, borrowed_book_path(book), class: '' %>
            </td>
            <td><%= book.borrowered_at.strftime("%B %d, %Y") %></td>
            <td><%= distance_of_time_in_words(Time.current, book.borrowered_at + 2.weeks) %> remaining</td>
            <td>
            <% book.comments.each do |comment| %>
                <% if comment.user_id == current_user.id %>
                <%= comment.content %><br>
                <% end %>
            <% end %>
            </td>
            <td>
            <%= button_to 'Return', return_borrowed_book_path(book), method: :post, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>You have no borrowed books.</p>
<% end %>

app/views/borrowed_books/show.html.erb
<div class='text-start flex d-flex-column'>
    <h1> <%= @book.title %> </h1>
    <p class="">Borrowed at: <%= @book.borrowered_at.strftime("%B %d, %Y") %></p>
    <p class="">Time remaining: <%= distance_of_time_in_words(Time.current, @book.borrowered_at + 2.weeks) %></p>

    <h3 class="">Comments</h3>
    <ul class="list-unstyled">
    <% @book.comments.each do |comment| %>
        <li class="d-flex justify-content-start align-items-center gap-5 py-2">
        <strong><%= comment.user.email %>:</strong> <%= comment.content %>
        <% if comment.user == current_user || current_user.is_admin? %>
            <%= button_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
        <% end %>
        </li>
    <% end %>
    </ul>

    <h3 class="">Leave a Comment</h3>
    <%= form_with url: comment_borrowed_book_path(@book), method: :post, local: true do |form| %>
    <%= form.text_area :comment, placeholder: "Enter your comment", rows: 4, class: 'form-control' %>
    <%= form.submit 'Post Comment', class: 'btn btn-primary mt-2' %>
    <% end %>
</div>