config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    sessions: "users/sessions"
  }, path: "auth", path_names: {
    sign_in: "login",
    sign_out: "logout",
    password: "secret",
    confirmation: "verification",
    unlock: "unblock",
    registration: "register",
    sign_up: "cmon_let_me_in"
  }

  namespace :api do
    resources :users
    resources :books
  end

  resources :books do
    member do
      post :borrow
      resources :comments, only: [ :destroy ]
    end
  end

  resources :borrowed_books, only: [ :index, :show, :update ] do
    member do
      post :return
      post :comment
    end
  end

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.all
    if params[:category].present?
      @books = Book.joins(:categories).where(categories: { id: params[:category] })
    else
      @books = Book.all
    end
  end
end

app/views/home/index.html.erb
<div class="container my-5">
    <% if current_user.is_admin? %>
    <div class="row justify-content-center">
      <div class="col-md-8 text-center">
        <div class="mb-3">
          <%= link_to "Admin Dashboard", admin_root_path, class: "btn btn-primary btn-lg mx-2" %>
        </div>
      </div>
    </div>
    <% end %>
  <%= render 'shared/category_filter' %>
  <h1 class="text-center mb-4">Books</h1>
  <% if @books.any? %>
    <div class="table-responsive">
      <table class="table table-striped table-bordered align-middle">
        <thead class="table-dark">
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Categories</th>
            <th>Comments</th>
            <% if current_user.number_of_books <= 2 %>
            <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.author %></td>
              <td><%= book.categories.map(&:name).join(", ") %></td>
              <td><%= book.comments.map(&:content).join("<br>").html_safe %></td>
              <td>
                <%= button_to "#{book.borrowed? ? 'Unavailable' : 'Borrow Book'}", borrow_book_path(book), method: :post, class: "btn #{book.borrowed? ? 'btn-secondary' : 'btn-primary'} btn-sm" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p class="text-center">No books available at the moment.</p>
  <% end %>
</div>